# Build and deploy pipeline
# https://aka.ms/yaml

trigger:
  - stage
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: Checkout@1
    displayName: 'Checkout source code'

  - script: |
      echo $(containerRegistryPassword) | docker login $(containerRegistryServer) --username $(containerRegistryUsername) --password-stdin
    displayName: 'Azure Container Registry login'

  - task: Docker@2
    displayName: 'Build and push Docker image'
    inputs:
      repository: '$(containerRegistryServer)/$(imageName)'
      arguments: '--target $(target)'
      tags: |
        latest
