# Build and deploy pipeline
# https://aka.ms/yaml

trigger:
  - stage
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    displayName: 'Checkout source code'

  - script: |
      echo $(containerRegistryPassword) | docker login $(containerRegistryServer) --username $(containerRegistryUsername) --password-stdin
    displayName: 'Azure Container Registry login'

  - task: Docker@2
    displayName: 'Build Docker image'
    inputs:
      command: 'build'
      repository: '$(containerRegistryServer)/$(imageName)'
      arguments: '--target $(target)'
      tags: |
        latest

  - task: Docker@2
    displayName: 'Push Docker image'
    inputs:
      command: 'push'
      repository: '$(containerRegistryServer)/$(imageName)'
      tags: |
        latest
