# Default settings for all host machines

#System Settings
php_version: "8.2"
php_modules: [ "fpm", "common", "mysql", "mbstring", "xml", "gd", "curl", "imagick", "zip", "memcached", "redis", "opcache" ]

node_version: "18.x"