### Settings for local host machine

# MySQL Settings
mysql_host: "localhost"
mysql_db: "wp_wp-starter"
mysql_user: "root"
mysql_password: ""

# HTTP Settings
http_host: "starter.local"
http_port: "80"

# Location Settings
project_path: "/var/www/wp-starter"
plugin_path: "{{ project_path }}/wp-content/plugins/ewplugin"
theme_path: "{{ project_path }}/wp-content/themes/ew-theme"