server {
    listen 80;
    listen [::]:80;

    # Limit file upload to 8 MB
    client_max_body_size 8M;

    # Route to project code root (where page is loaded from)
    root /var/www/html;
    index index.php index.html index.htm;

    # Sets domain for this configuration
    # Every request with this domain will be routed to this conf
    server_name ${EW_DOMAIN_NAME};

    # Log to standard
    access_log /dev/stdout;
    error_log /dev/stderr;

    # Run all static files directly
    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    # Handle .php files through PHP-FPM service
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    # Browser cache for files with this suffix
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|avif|webp|svg|ttf|woff|woff2)$ {
        expires max;
        log_not_found off;
    }

    # Don't log favicon requests
    location = /favicon.ico {
        log_not_found off;
        access_log off;
    }

    # Allow access to robots and don't log requests
    location = /robots.txt {
        allow all;
        log_not_found off;
        access_log off;
    }

    # Hide any hidden files (.envs, .gits...)
    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }

    # Hide any backup, SQL dump files or logs that came here accidentally
    location ~ ^.+\.(log|sql|bak|php~|php#|php.save|php.swp|php.swo)$ {
        deny all;
        access_log off;
        log_not_found off;
    }

    # Hide the nginx version
    server_tokens off;

    # Hide the PHP version
    fastcgi_hide_header X-Powered-By;
    proxy_hide_header X-Powered-By;

    # Prevent website loading in an iframe
    add_header X-Frame-Options SAMEORIGIN;

    # Turns off directory listing
    autoindex off;

    # Include project specific configuration (usually updated by cache and security plugins)
    include /var/www/html/*.conf;
}
