# PHP namespace name
# [PascalCase]
namespace="EWStarter"

# occurrence of plugin name in file names
# [kebab-case]
pluginNameForFileNames="ewplugin"

# occurrence of plugin name in function names
# [snake_case]
pluginNameForFunctions="ew_plugin"

# theme folder and files occurrences name
# [kebab-case]
themeNameForFileNames="ew-theme"

# API route base name (<domain>/wp-json/<wp-ew>/v1/), usually short and prefixed with wp
# [kebab-case]
baseRoute="wp-ew"

# local domain name
# [kebab-case]
webAppServerDomain="wp-starter.ew.local"
