# PHP namespace name
# [PascalCase]
namespace="FilipMarencic"

# occurrence of plugin name in file names
# [kebab-case]
pluginNameForFileNames="filip-marencic"

# occurrence of plugin name in function names
# [snake_case]
pluginNameForFunctions="filip_marencic"

# theme folder and files occurrences name
# [kebab-case]
themeNameForFileNames="filip-marencic"

# API route base name (<domain>/wp-json/<wp-ew>/v1/), usually short and prefixed with wp
# [kebab-case]
baseRoute="wp-fm"

# local domain name
# [kebab-case]
webAppServerDomain="filipmarencic.ew.local"
